route:
  receiver: admin

receivers: 
  - name: admin
    email_config:
      - to : 'sumedhak.da.23@nitj.ac.in'
      - from: 'sumedhxgg@gmail.com'  
      - smarthost: smtp.gmail.com:587
      - auth_username: 'sumedhxgg@gmail.com'
      - auth_identity: '16-digit password'

